# Use an official Node.js image
FROM node:18

# Set working directory in the container
WORKDIR /app

COPY ./package.json ./

RUN npm install -g

COPY ./ ./


# Expose the development port
EXPOSE 8080

# Run the Vue.js app in development mode
CMD ["npm", "run", "serve-ui"]
